### ISSUE TITLE
请详细列出导入SDK所需要的配置步骤可以么 ？

### ISSUE THREAD

**Issue by gavinfan** [heloyue/TCWeiboSDK#7]
按照官方的文档根本都不能够运行成功， 最起码需要导入3个库， 都没有列出来， 除了demo中的三个库， 请问还需要在工程中做些什么 ？

**Comment by SeanChense** [comment]
1.要把TCWeiboSDK目录下的 a 文件删除到只剩libTCWeiboSDK.a(我就是这样
2.引入库：Account.framework, Security.framework和Social.framework。
